"""add_task_masters_and_enhancements

Revision ID: 9c4c96667bcc
Revises: 2cd8588e3f79
Create Date: 2026-02-09 17:58:44.129796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4c96667bcc'
down_revision = '2cd8588e3f79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_masters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # Add columns with server defaults for existing rows
    op.add_column('task_entries', sa.Column('is_overtime', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('task_entries', sa.Column('overtime_hours', sa.Numeric(precision=4, scale=2), nullable=False, server_default='0'))
    op.add_column('task_sub_entries', sa.Column('task_master_id', sa.UUID(), nullable=True))
    op.add_column('task_sub_entries', sa.Column('productive', sa.Boolean(), nullable=False, server_default='true'))
    
    # Remove server defaults after adding columns (so new inserts must provide values)
    op.alter_column('task_entries', 'is_overtime', server_default=None)
    op.alter_column('task_entries', 'overtime_hours', server_default=None)
    op.alter_column('task_sub_entries', 'productive', server_default=None)
    
    op.create_foreign_key(None, 'task_sub_entries', 'task_masters', ['task_master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task_sub_entries', type_='foreignkey')
    op.drop_column('task_sub_entries', 'productive')
    op.drop_column('task_sub_entries', 'task_master_id')
    op.drop_column('task_entries', 'overtime_hours')
    op.drop_column('task_entries', 'is_overtime')
    op.drop_table('task_masters')
    # ### end Alembic commands ###
