"""add_is_profitable_to_task_masters

Revision ID: e4292785391d
Revises: 9c4c96667bcc
Create Date: 2026-02-09 18:45:32.989361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4292785391d'
down_revision = '9c4c96667bcc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default for existing rows
    op.add_column('task_masters', sa.Column('is_profitable', sa.Boolean(), nullable=False, server_default='true'))
    # Remove server default after adding column
    op.alter_column('task_masters', 'is_profitable', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_masters', 'is_profitable')
    # ### end Alembic commands ###
