"""add_password_reset_tokens

Revision ID: 9f2b54a4452b
Revises: b1a4172fd748
Create Date: 2026-02-10 07:17:14.406541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f2b54a4452b'
down_revision = 'b1a4172fd748'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
